# SPDX-License-Identifier: MIT

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "liot"
BBFILE_PATTERN_liot = "^${LAYERDIR}/"
BBFILE_PRIORITY_liot = "20"

LAYERDEPENDS_liot = "core snapd ampliphy phytec lts-go-mixin cyclonedx"
LAYERSERIES_COMPAT_liot = "scarthgap"

INHERIT += "cyclonedx-export"
CYCLONEDX_SPEC_VERSION = "1.6"

CYCLONEDX_EXPORT_DIR ?= "${DEPLOY_DIR_IMAGE}"
# Try to set meaningful default filenames for both image and non-image recipes
CYCLONEDX_EXPORT_BASENAME ?= "${CYCLONEDX_EXPORT_DIR}/${@d.getVar('IMAGE_NAME') or d.getVar('IMAGE_BASENAME') or d.getVar('PN')}.cyclonedx"
CYCLONEDX_EXPORT_SBOM ?= "${CYCLONEDX_EXPORT_BASENAME}.bom.json"
CYCLONEDX_EXPORT_VEX ?= "${CYCLONEDX_EXPORT_BASENAME}.vex.json"
# Create symlinks for image recipes similar to the image files by default
IMAGE_LINK_NAME ??= ""
CYCLONEDX_EXPORT_SBOM_LINK ?= "${@'${IMAGE_LINK_NAME}.cyclonedx.bom.json' if d.getVar('IMAGE_LINK_NAME') else ''}"
CYCLONEDX_EXPORT_VEX_LINK ?= "${@'${IMAGE_LINK_NAME}.cyclonedx.vex.json' if d.getVar('IMAGE_LINK_NAME') else ''}"

INHERIT:remove = "create-spdx"
INHERIT += "create-spdx-3.0"
SPDX_INCLUDE_COMPILED_SOURCES:pn-${PREFERRED_PROVIDER_virtual/kernel} = "1"

BBMASK:append:mx8mm-nxp-bsp = " meta-imx/meta-imx-bsp/recipes-bsp/firmware-imx/firmware-nxp-wifi_%.bbappend"

# WORKAROUND: Override the DISTRO_VERSION, as this is set by other overrides in
# meta-ampliphy
DISTROOVERRIDES .= ":liot"
DISTRO_VERSION:liot = "2026-09-15"
RAUC_BUNDLE_VERSION = "${DISTRO_VERSION}"
