# SPDX-License-Identifier: MIT

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "liot"
BBFILE_PATTERN_liot = "^${LAYERDIR}/"
BBFILE_PRIORITY_liot = "6"

LAYERDEPENDS_liot = "core"
LAYERSERIES_COMPAT_liot = "scarthgap"
